### ISSUE TITLE
Windows Defender exclusion

### ISSUE THREAD

**Issue by timeyers** [9xc/cromosome-dropper#1]
Does this add dropped files folder to WD exclusion?

**Comment by 9xc** [comment]
If you mean add itself as an exclusion on execution then no.

timeyers ***@***.***> schrieb am Do. 11. Aug. 2022 um 19:25:

**Comment by timeyers** [comment]
I mean using UAC bypass to add exclusions, then download and run payload

**Comment by 9xc** [comment]
I can maybe add that

timeyers ***@***.***> schrieb am Do. 11. Aug. 2022 um 21:19:
